import { createStyles } from "@mantine/core";
import home from "../../assets/home.png";
import img from "../../assets/achievements.jpg";
import img2 from "../../assets/testBg.png";
import img3 from "../../assets/testcard.png";
export const useStyles = createStyles((theme) => ({
  top: {
    height: "680px",
    backgroundImage: `url(${home})`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundSize: "100% 680px",
    color: "white",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    [`@media (max-width: 1000px)`]: {
      height: "500px",
      backgroundSize: "100% 500px",
    },
    [`@media (max-width: 800px)`]: {
      height: "450px",
      backgroundSize: "250% 450px",
    },
  },
  topContent: {
    width: "40%",
    marginLeft: "70px",
    [`@media (max-width: 800px)`]: {
      width: "70%",
      marginLeft: "10px",
      marginTop: "auto",
      paddingBottom: "20px",
    },
  },
  title1: {
    display: "flex",
    gap: "10px",
    borderBottom: "3px solid black",
    alignSelf: "flex-start",
    paddingBottom: "2px",
    position: "relative",
    ":after": {
      content: '""',
      width: "80%",
      position: "absolute",
      bottom: -10,
      height: "3px",
      backgroundColor: theme.colors.cyan,
    },
  },
  title2: {
    display: "flex",
    gap: "10px",
    borderBottom: "3px solid black",
    // alignSelf: "center",
    paddingBottom: "2px",
    flexGrow: 1,
    width: "250px",
    margin: "auto",
    marginBottom: "10px",
    justifyContent: "center",
    position: "relative",
    ":after": {
      content: '""',
      width: "80%",
      position: "absolute",
      bottom: -10,
      height: "3px",
      backgroundColor: theme.colors.cyan,
    },
  },
  achievement: {
    padding: "50px",
    backgroundImage: `url(${img})`,
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    position: "relative",
    color: "white",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    gap: "20px",
    fontSize: "22px",
    "& > *": {
      zIndex: 99,
      position: "relative",
    },
    ":after": {
      content: '""',
      position: "absolute",
      width: "100%",
      height: "100%",
      zIndex: 0,
      top: 0,
      right: 0,
      backgroundColor: "rgb(26, 87, 143, 0.7)",
    },
  },
  ach: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    // padding: "30px",
    gap: "10px",
    height: "280px",
    width: "280px",
    "& > img": {
      width: "70px",
    },
    ":before": {
      content: '""',
      position: "absolute",
      width: "100%",
      height: "40%",
      top: 0,
      left: 0,
      border: "2px solid white",
      zIndex: 10,
      borderBottom: "none",
    },
    ":after": {
      content: '""',
      position: "absolute",
      width: "100%",
      height: "40%",
      bottom: 0,
      left: 0,
      border: "2px solid white",
      zIndex: 10,
      borderTop: "none",
    },
  },
  tests: {
    backgroundImage: `url(${img2})`,
    backgroundRepeat: "no-repeat",
    height: "500px",
    padding: "50px",
    backgroundSize: "100% 600px",
    [`@media (max-width: 800px)`]: {
      padding: "10px",
    },
  },
  comment: {
    position: "relative",
    ":after": {
      content: '""',
      position: "absolute",
      bottom: -37,
      left: 10,
      borderWidth: "25px",
      borderStyle: "solid",
      borderColor: "#ffff transparent transparent transparent",
    },
  },
}));
